# currently needed for the prerelease of microbundle
npmRegistryServer: 'https://registry.wardpeet.dev'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-sources.cjs
